export default {
  common_messages: {
    powered_by: "Powered by Bett House",
    error_toast: "error",
    success_toast: "success",
    something_went: "Something Went Wrong !",
  },
  org_screen: {
    title: "Organisation",
    org_placeholder: "Enter organisation code",
    short_message: "Short name provided by the organisation",
    error_org: "Please enter org code",
  },
  login_screen: {
    title: "Login",
    username_title: "Username/Email",
    password_title: "Password",
    username_placeholder: "Enter username or email",
    password_placeholder: "Enter password",
    error_username: "Please enter username",
    error_password: "Please enter password",
    email_error: "Email is Not Correct",
  },
  forgotpass_screen: {
    title: "Forgot Password",
    username_title: "Please enter your email address",
    username_placeholder: "Enter your email address",
    reset_message: "Password Reset Successful",
  },
  signup_screen: {
    title: "Register",
    firstname_title: "First Name",
    firstname_placeholder: "Enter your first name",
    lastname_title: "Last Name",
    lastname_placeholder: "Enter your last name",
    username_title: "Email",
    username_placeholder: "Enter your email",
    password_title: "Create Password",
    password_placeholder: "Create new password",
    confirm_password_title: "Confirm Password",
    confirm_password_placeholder: "Please confirm your password",
    error_username: "Please enter username",
    error_password: "Please enter password",
    error_firstname: "Please enter firstname",
    error_lastname: "Please enter lastname",
    error_confirmpass: "Please enter confirm pass",
    error_passmatch: "Password doesn't match",
    success_message: "Account Registered Successful",
  },
  profile_screen: {
    firstname_title: "First Name",
    firstname_placeholder: "Please enter username",
    lastname_title: "Last Name",
    lastname_placeholder: "Please enter lastname",
    username_title: "Email",
    username_placeholder: "Please enter email",
    phone_title: "Phone",
    phone_placeholder: "Please enter phone",
    city_title: "City",
    city_placeholder: "Please enter city",
    state_title: "State",
    state_placeholder: "Please enter state",
    country_title: "Country",
    country_placeholder: "Please enter country",
  },
  search_screen: {
    no_activity_msg: "No activty found !",
  },
  create_activity_screen: {
    group_title: "Group",
    post_title: "Post Title",
    group_error: "Select Group",
    title_error: "Enter Title",
    description_error: "Enter Description",
  },
};
